// Brand research — the "intelligence" layer. Turns just a brand/domain into a
// tailored measurement plan: the real buyer questions (prompts) people ask AI
// in that category, plus the real competitors — generated by an LLM instead of
// a hardcoded starter set. This is what makes the tool work for ANY brand /
// industry with zero manual setup.
//
// Uses whichever key is configured (OpenAI or Anthropic). With no key it falls
// back to null so the caller can use the static starter set (demo).

import { openaiKey } from './engines/openai';
import { anthropicKey } from './engines/anthropic';
import type { PromptTopic } from './types';

export interface BrandResearch {
  brandLabel: string;
  domain?: string;
  category: string;        // e.g. "D2C beauty / skincare"
  vertical: string;        // free-text industry label
  positioning: string;     // one line on how the brand positions
  competitors: { label: string; domain?: string }[];
  topics: PromptTopic[];   // tailored buyer questions
  source: 'llm' | 'fallback';
}

// ---- provider-agnostic JSON completion (no web tool needed for research) ----
async function llmJson(system: string, user: string): Promise<any | null> {
  const ok = openaiKey();
  if (ok) {
    const model = (import.meta as any).env?.OPENAI_MODEL ?? process.env.OPENAI_MODEL ?? 'gpt-4o';
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${ok}` },
      body: JSON.stringify({
        model,
        response_format: { type: 'json_object' },
        messages: [{ role: 'system', content: system }, { role: 'user', content: user }],
        temperature: 0.2,
      }),
    });
    if (!res.ok) throw new Error(`OpenAI research ${res.status}: ${(await res.text().catch(() => '')).slice(0, 200)}`);
    const data: any = await res.json();
    return JSON.parse(data?.choices?.[0]?.message?.content ?? '{}');
  }
  const ak = anthropicKey();
  if (ak) {
    const model = (import.meta as any).env?.ANTHROPIC_MODEL ?? process.env.ANTHROPIC_MODEL ?? 'claude-sonnet-4-6';
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': ak, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({
        model, max_tokens: 2000, system,
        messages: [{ role: 'user', content: `${user}\n\nRespond with ONLY a JSON object, no prose.` }],
      }),
    });
    if (!res.ok) throw new Error(`Anthropic research ${res.status}: ${(await res.text().catch(() => '')).slice(0, 200)}`);
    const data: any = await res.json();
    const text = (data?.content ?? []).filter((b: any) => b.type === 'text').map((b: any) => b.text).join('');
    const json = text.slice(text.indexOf('{'), text.lastIndexOf('}') + 1);
    return JSON.parse(json);
  }
  return null;
}

export interface ResearchInput {
  brandLabel: string;
  domain?: string;
  locale?: string;
  maxTopics?: number;
  promptsPerTopic?: number;
}

export async function researchBrand(input: ResearchInput): Promise<BrandResearch | null> {
  const locale = input.locale || 'en-IN';
  const maxTopics = Math.min(Math.max(input.maxTopics ?? 8, 4), 12);
  const ppt = Math.min(Math.max(input.promptsPerTopic ?? 2, 1), 3);

  const system =
    'You are an AEO (Answer Engine Optimization) analyst. You research a brand and design a measurement plan for how visible it is in AI assistants (ChatGPT, Gemini, Perplexity). ' +
    'You output strict JSON only.';
  const user =
    `Brand: "${input.brandLabel}"${input.domain ? ` (domain: ${input.domain})` : ''}. Market/locale: ${locale}.\n\n` +
    `Figure out what this brand sells and design a plan to measure its AI-search visibility.\n` +
    `Return JSON with this exact shape:\n` +
    `{\n` +
    `  "category": "short label of what they sell",\n` +
    `  "vertical": "industry label",\n` +
    `  "positioning": "one sentence on how they position",\n` +
    `  "competitors": [{"label":"Brand","domain":"brand.com"} ... 5 to 6 real direct competitors in this market],\n` +
    `  "topics": [ ${maxTopics} objects like {"topic":"short category label","category":"product category","intent":"commercial|informational|navigational","prompts":[${ppt} natural buyer questions a real shopper would type into an AI assistant, localized to ${locale}, that should surface brands but WITHOUT naming "${input.brandLabel}" or any specific brand]} ]\n` +
    `}\n` +
    `Prompts must be brand-agnostic category questions (e.g. "best vitamin C serum in India"), high purchase-intent, and varied. No commentary.`;

  let raw: any;
  try { raw = await llmJson(system, user); }
  catch (e) { throw e; }
  if (!raw) return null;

  const topics: PromptTopic[] = Array.isArray(raw.topics) ? raw.topics
    .filter((t: any) => t && t.topic && Array.isArray(t.prompts) && t.prompts.length)
    .slice(0, maxTopics)
    .map((t: any) => ({
      topic: String(t.topic),
      category: t.category ? String(t.category) : undefined,
      intent: ['commercial', 'informational', 'navigational'].includes(t.intent) ? t.intent : 'commercial',
      prompts: t.prompts.map((p: any) => String(p)).slice(0, ppt),
    })) : [];

  const competitors = Array.isArray(raw.competitors) ? raw.competitors
    .filter((c: any) => c && (c.label || typeof c === 'string'))
    .map((c: any) => (typeof c === 'string' ? { label: c } : { label: String(c.label), domain: c.domain ? String(c.domain) : undefined }))
    .slice(0, 6) : [];

  if (!topics.length) return null;

  return {
    brandLabel: input.brandLabel,
    domain: input.domain,
    category: String(raw.category ?? ''),
    vertical: String(raw.vertical ?? ''),
    positioning: String(raw.positioning ?? ''),
    competitors,
    topics,
    source: 'llm',
  };
}
